locale = "uk"
label = "Українська"
weight = 1
title = "Львівський центр професійно-технічної освіти ДСЗ"

[params]
  displayName = "Українська"
  isoCode = "uk"
  rtl = false
  dateFormat = "02.01.2006"
  description = "Навчання за робітничими професіями, курси підвищення кваліфікації, дуальна та дистанційна освіта. Львівський центр ПТО ДСЗ."
